### ISSUE TITLE
Improvement: Vermeidung Lawinenauslösung

### ISSUE THREAD

**Issue by GrafRudi** [kuecande/alpinexperience#3]
In der Zusammenfassung schreibst Du, dass Lawinenauslösungen zu vermeiden sind, dies halte ich für ein so wichtigen Punkt, das er auf der ersten Motivationsfolie auch erscheinen sollte.

Zwei Antennengeräte sind als "gelb" eingestuft, ist das die aktuelle Lehermeinung? Hintergrund: bei meiner letzten Ausbildung hatten die Teilnehmer mit demm BCA Tracker? und Arva Evo3?, die schnellsten Suchergebnisse, da bei den neueren Geräten es immer wieder zu Verzögerungen im Gerät kam. Das mehr an "Features" in den modernen Geräten war oft verwirrend.

Folie 7: bis 2009 würde ich rauslassen/abdecken, das verwirrt die TN nur
Hast Du irgendwo ein Bild wo man die ersten 3 Phasen aus einem Bild sieht, inklusive der "Geschwindigkeit"?

Gute Arbeit
Rudi

**Comment by kuecande** [comment]
1. Statement auf die erste Motivationsslide rübergeholt
2. Es gibt die generelle Empfehlung, bei Neuanschaffung auf 3-Antennen-Geräte zu setzen
slide 9 zeigt die detaillierte Ergebnisse des letzten Verfügbaren DAV-Tests 17/18
=> keine Änderung dieser slide
3. Alte IKAR Suchphasen Grafik durch neue ersetzt, in der man auch Präzsion vs. Geschwindigkeit sieht.
